### ISSUE TITLE
Modification of the original view position

### ISSUE THREAD

**Issue by dentvii** [Mijick/PopupView#100]
![ScreenRecording2024-05-21at15 17 24-ezgif com-video-to-gif-converter](https://github.com/Mijick/PopupView/assets/87960/5c1f22cf-c901-451d-a7e7-86beda576041)

## Issue Description

When implementing a pop-up, the view in which it is hosted is altered. The view should only be as big as its container, but when the pop-up is implemented, it shifts to the top leading position, modifying the view itself.

## Steps to Reproduce

1. **Create a small view**: 
   - Create a view that is relatively small.
2. **Implement the pop-up**: 
   - Add the pop-up to the small view.

### Observed Behavior

- If the view is small, the pop-up is positioned at the top leading.
- If the view is not small, the pop-up is centered.
- This change does not affect the behavior of the pop-up but modifies the position of the view.

## Suggested Solution

Wrap the view in a container to protect its location and size, especially if the view is small. This might be an edge case, as most developers will implement a full view to start their application, but it's worth noting that the original view is modified.

**Comment by FulcrumOne** [comment]
Good finding @dentvii, thanks! Patch-2.4.2 branch solves this problem too
