### ISSUE TITLE
Add visionOS support

### ISSUE THREAD

**Issue by FulcrumOne** [Mijick/PopupView#107]

**Comment by mschinis** [comment]
Hi, is there a timeline for this at all? I would like to start using this in a cross-platform app, which includes visionOS support

**Comment by FulcrumOne** [comment]
Hey, there is. According to our roadmap, we should start the development process at the end of this month (after we finish updating [CameraView](https://github.com/Mijick/CameraView) and [NavigationView](https://github.com/Mijick/NavigationView)). We expect to have it completed by the 10th July, but the dates may shift slightly as we're working on our website and other projects in the meantime.

Have a great day,
T.K.

**Comment by jay-jay-lama** [comment]
Hello @mschinis 
 
We've developed an initial version that is compatible with visionOS, available for testing on the branch named **patch-3.0.0**.
Currently, it supports presenting popups from a single WindowGroup item. But we are working on improving this functionality.

Have a great day,
A.P.
