### ISSUE TITLE
Fix the problem with the Apple sheet covering the popup

### ISSUE THREAD

**Issue by FulcrumOne** [Mijick/PopupView#110]

**Comment by dimitri-nik** [comment]
Any updates on when this will get resolved? Love this library

**Comment by FulcrumOne** [comment]
hey @dimitri-nik, thanks!

We start preferably next week (we still have some things to do in [NavigationView](https://github.com/Mijick/NavigationView) and [CameraView](https://github.com/Mijick/CameraView)). Sorry it takes so long, but our resources are very limited at the moment and we are also involved in several other projects 😅

Have a great day,
Tomasz

**Comment by slowbrewedmacchiato** [comment]
+1

**Comment by slowbrewedmacchiato** [comment]
Hi there,

Just wanted to find out if there was any update on this?

Regards.

**Comment by FulcrumOne** [comment]
hey @slowbrewedmacchiato,

I'm working on it right now

**Comment by FulcrumOne** [comment]
ok, it appears that I'm a person of little faith, because seems that I'll be able to fix it:
![CleanShot 2024-08-02 at 15 11 20](https://github.com/user-attachments/assets/b39fec3c-8d15-4b4e-90b1-d92e9a58cfb8)

**Comment by FulcrumOne** [comment]
@slowbrewedmacchiato @dimitri-nik,

It seems to be fixed in branch `patch-2.5.1`. Here is the code to make the fix work:
```Swift
import SwiftUI
import MijickPopupView

@main struct PopupView_Main: App {
    @UIApplicationDelegateAdaptor(AppDelegate.self) var appDelegate


    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
private extension PopupView_Main {
    func configurePopup(_ config: GlobalConfig) -> GlobalConfig { config
        .top { $0
            .cornerRadius(24)
            .dragGestureEnabled(true)
        }
        .centre { $0
            .tapOutsideToDismiss(false)
        }
        .bottom { $0
            .stackLimit(4)
        }
    }
}



class AppDelegate: NSObject, UIApplicationDelegate {
    func application(_ application: UIApplication, configurationForConnecting connectingSceneSession: UISceneSession, options: UIScene.ConnectionOptions) -> UISceneConfiguration {
        let sceneConfig = UISceneConfiguration(name: nil, sessionRole: connectingSceneSession.role)
        sceneConfig.delegateClass = PopupSceneDelegate.self
        return sceneConfig
    }
}
```

**Comment by FulcrumOne** [comment]
So in a nutshell - you need to remove .implementPopupView() from your MainView and declare a custom AppDelegate instead. Let me know if everything works as intended.

**Comment by dimitri-nik** [comment]
Hey @FulcrumOne tested it out quickly looks like its working as intended, thanks for the fix!

**Comment by slowbrewedmacchiato** [comment]
Thank you @FulcrumOne ! It worked.

Highly appreciate it.
