### ISSUE TITLE
Native like sheet resizing feature

### ISSUE THREAD

**Issue by jakub-kalamarz** [Mijick/PopupView#118]
It would be immensely beneficial to have a built-in capability to use UISheetPresentationController.Detent as an option for resizing the presented sheet on drag. This feature would significantly improve the user experience by providing more flexibility and control over the presented sheet's behavior.

**Comment by FulcrumOne** [comment]
Hey @jakub-kalamarz,

Could you please paste a video here showing how it should work? 

Thanks a million,
Tomasz

**Comment by jakub-kalamarz** [comment]
Hey, thanks for response.

This is the look and feel I would like to achieve when using your lib.


https://github.com/Mijick/PopupView/assets/34458752/7f3b80e2-e186-4c83-81ab-a9f9290c1519

**Comment by FulcrumOne** [comment]
oh, I see. I think there is no problem with including this in our library, so I'm adding it to our backlog 😉

**Comment by FulcrumOne** [comment]
hey @jakub-kalamarz,

I've started implementing your idea, but I need your confirmation whether I understood it correctly.
Let's say the initial popup is 200 px high and I use a drag gesture to make it bigger. To my understanding, the developer should be able to define the next size thresholds (like 300, 400 px or 150%, 250%), correct?

**Comment by FulcrumOne** [comment]
Implemented in version 2.7.0
