### ISSUE TITLE
Bug: Publishing changes from KeyboardManager

### ISSUE THREAD

**Issue by armoona** [Mijick/PopupView#120]
Occasionally, I get the following warning in XCode:

PopupView/Sources/Internal/Managers/KeyboardManager.swift:17 Publishing changes from within view updates is not allowed, this will cause undefined behavior.

- It happens without any calls to PopupView.
- It happens when the keyboard is dismissed by some view.

**Comment by jay-jay-lama** [comment]
Hello @armoona.
Could you please check branch `patch-3.0.1`? 
If it won't work please provide some example code that I can use to reproduce the problem and fix it.
