### ISSUE TITLE
Disable black overlay using configure?

### ISSUE THREAD

**Issue by praveenperera** [Mijick/PopupView#133]
For most situations I think the transparent black overlay that dims the screen makes sense, but would it be possible to disable this with the `configure`. Some situations I don't want the entire screen dimmed on a notification type popup (top and bottom).

**Comment by FulcrumOne** [comment]
Hey @praveenperera,

This is possible, please check the code below:

```Swift
TopPopup_Notification()
    .showAndStack()
    .hideOverlay()
```

I can see that this is not very user-friendly, so I will probably move it to a popup declaration in the future versions.

Have a nice day,
T.K.

**Comment by praveenperera** [comment]
Oh sorry about that must have missed it in the readme. But ya probably makes more sense in the configure?
