### ISSUE TITLE
Dismiss on touching outside?

### ISSUE THREAD

**Issue by gemiren** [Mijick/PopupView#25]
Congratulations on this awesome library! The only thing missing is to dismiss the popup when touching outside. Would be great if this feature can be added.

**Comment by akardas16** [comment]
> Congratulations on this awesome library! The only thing missing is to dismiss the popup when touching outside. Would be great if this feature can be added.

it has already. See below code 
`struct myPop: CentrePopup {
  
    var onClicked:() -> Void
    func configurePopup(popup: CentrePopupConfig) -> CentrePopupConfig {
        popup.tapOutsideToDismiss(true).horizontalPadding(28)
    }
    func createContent() -> some View {
        VStack(spacing: 12) {
            LottieView(name: "warning").frame(width: 48, height: 48).padding(.bottom)
           
            Text("You will loss your progress if you don't finish the exercise!")

            Capsule(style: .circular).fill(Color(hex: "#08203e")).frame(maxWidth: .infinity).frame(height: 48)
                .overlay {
                    Text("Finish").font(.lato(.bold, size: 20)).foregroundColor(.white)
                }
        
                .onTapWithBounce {
                    dismiss()
                    onClicked()
                }
            Button {
                dismiss()
            } label: {
                Text("Cancel").font(.lato(.bold, size: 20)).foregroundColor(Color(hex: "#08203e"))
            }

          
            
    
        }
        .padding(.vertical)
        .padding(.vertical)
        .padding(.horizontal, 16)
    }
}`

**Comment by gemiren** [comment]
But that only applies to CenterPopup. Can we have that for BottomPopup and TopPopup?

**Comment by FulcrumOne** [comment]
Hi @gemiren! 

The improvement you wrote about has just been implemented. Enjoy using the library and let us know in case you see any room for improvement :)

Have a nice day,
T.K.

**Comment by gemiren** [comment]
You guys rock!
