### ISSUE TITLE
Automatically falling back to Main Thread rendering engine...

### ISSUE THREAD

**Issue by akardas16** [Mijick/PopupView#26]
Hi, thanks for this amazing library. When I present popup view, I get below log in Xcode.
Automatically falling back to Main Thread rendering engine. This fallback comes with some additional performance
overhead, which can be reduced by manually specifying that this animation should always use the Main Thread engine.

**Comment by FulcrumOne** [comment]
Hi @akardas16, could you please send me the code to reproduce the above state? 

Thanks
