### ISSUE TITLE
BottomPopup placed under sheet

### ISSUE THREAD

**Issue by shervinkoushan** [Mijick/PopupView#28]
Hi, very nice work!

I only have one issue, the BottomPopup is placed under other sheets. 

So if I show a sheet, then present a BottomPopup, I have to dismiss the sheet for the BottomPopup to be visible.

**Comment by FulcrumOne** [comment]
Hi! 
I'm afraid that we can't "fix" it in any way - Apple's sheets were designed to be on the top of everything, so unfortunately they wont work with PopupView at all.

**Comment by shervinkoushan** [comment]
I tried to overcome this now by using a BottomPopup instead of a sheet. Now the second BottomPopup is shown, but I have an issue with the height. The first popup has `contentFillsWholeHeight` set to true, but the second one does not. Showing the second one will make the first one scale down to the size of the second one.

Just to make it clear:
BottomPopup 1 presented (max height)
Navigate to page inside popup
BottomPopup 2 presented (normal height) -> BottomPopup 1 scales down to normal height
