### ISSUE TITLE
Shift up the screen when the keyboard is opened.

### ISSUE THREAD

**Issue by gemiren** [Mijick/PopupView#29]
If I have a TextEditor on the bottom popup, and the TextEditor is focused, the keyboard doesn't open. I think this is because the bottom PopupView doesn't shift up. Can we make the screen shift up when the keyboard is opened? Thanks.

**Comment by FulcrumOne** [comment]
Hi. This #32 should fix your issue

**Comment by mny459** [comment]
How to disable TopPopup move up when keyboard show
