### ISSUE TITLE
PopupView size not updated after screen rotation.

### ISSUE THREAD

**Issue by gemiren** [Mijick/PopupView#30]
Steps to reproduce:
1, Start the app when the phone is in portrait mode.
2, Rotate the phone to landscape mode.
3, Open the bottom PopupView.

The bottom PopupView doesn't span the full screen width. Instead, it displays a shadow strip in the center of the screen with full height.

**Comment by FulcrumOne** [comment]
Hi. This #32 also should fix your issue
