### ISSUE TITLE
UIScreen.main.bounds doesn't work for iPad and Mac

### ISSUE THREAD

**Issue by StefanCosminR** [Mijick/PopupView#33]
Manually computing the screen width limits the usage of the library only for the iPhone and it's not the ideal way for SwiftUI. On iPad, in split screen or with stage manager, UIScreen.main.bounds gives the width of the entire screen, not the width of the app's window.

![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-05-22 at 12 59 38](https://github.com/Mijick/PopupView/assets/17311242/a9758b3c-773e-4c3a-a0b1-4222ca336ccf)

The fix is actually quite simple, mostly removing some .frame modifiers, like in this example

<img width="786" alt="Screenshot 2023-05-22 at 13 00 24" src="https://github.com/Mijick/PopupView/assets/17311242/ff7277fb-d404-4595-babd-4c622224ef13">

And now it looks good everywhere.

![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-05-22 at 13 00 18](https://github.com/Mijick/PopupView/assets/17311242/c0bdb86e-bfc9-4efe-a283-00349579dfd5)

The background view has the same problem, more apparent on the Mac.

![Screenshot 2023-05-22 at 13 27 51](https://github.com/Mijick/PopupView/assets/17311242/452d18a4-c0cf-40cd-b0f8-c1963cc57780)

But this too can be fixed quite easily

![Screenshot 2023-05-22 at 13 28 10](https://github.com/Mijick/PopupView/assets/17311242/8c70391c-0326-4fe7-990e-0a14ba641bb9)
<img width="955" alt="Screenshot 2023-05-22 at 13 28 16" src="https://github.com/Mijick/PopupView/assets/17311242/520093bd-ec39-4495-9fd6-d4c78667a88f">

I can open a pull request with these changes if that's ok for you

**Comment by FulcrumOne** [comment]
Hi!
Thanks a lot for this amazing post. To be honest with you, this library was never intended to run on MacOS, so that's why I declared it that way. Thanks again for your PR, I'll check it after my work and merge it with main. 
Have a nice day!

**Comment by FulcrumOne** [comment]
Hey @StefanCosminR, the bug should be fixed in the main branch. Thanks again for your help!
