### ISSUE TITLE
TopPopup White Safe Area (See Screenshot)

### ISSUE THREAD

**Issue by 9ae8sdf76** [Mijick/PopupView#37]
I created the following "alert" popup, and when it displays, the safe area at the top is white, despite my background being dark. I would expect any background to be using .clear by default. As a work around, I have implemented my own PopupConfig.

<img width="523" alt="Screenshot 2023-06-01 at 8 08 44 AM" src="https://github.com/Mijick/PopupView/assets/2528463/95c55394-e67a-482f-b85a-4f65ae7da370">

**Comment by FulcrumOne** [comment]
Hi. Can you share your code regarding this example? I have just tested something similar and every time the view is correct, like on the image below

![IMG_B0F0320E577C-1](https://github.com/Mijick/PopupView/assets/23524947/15f7f651-b58a-4ea9-84c6-81489b3d8e35)

**Comment by FulcrumOne** [comment]
@9ae8sdf76, hmm, weird, because it works in my case. Try another solution then - remove that background modifier completely from your code, and try to call this method (above your `createContent()` function)

```
func configurePopup(popup: TopPopupConfig) -> TopPopupConfig {
     popup.backgroundColour(Color("Primary Background"))
}
```

**Comment by 9ae8sdf76** [comment]
It works as expected when I use the `configurePopup()` and define the `backgroundColour()` myself.
