### ISSUE TITLE
iOS14 CenterPopupView do not display

### ISSUE THREAD

**Issue by jackiehu** [Mijick/PopupView#47]
iOS14 CenterPopupView do not display

**Comment by FulcrumOne** [comment]
Hey @jackiehu,

Unfortunately my current version of macOS doesn't support iOS version lower than 15.0. Could you please share details about this bug? Does it affect only CenterPopupView or other types as well?

**Comment by FulcrumOne** [comment]
Fixed with patch 2.2.2
