### ISSUE TITLE
Pod not update the latest  code 

### ISSUE THREAD

**Issue by KavinduDissanayake** [Mijick/PopupView#50]
pod 'Mijick_PopupView'  

After pod install 
I have to change 
import  PopView to Mijick_PopupView

but I got this error. please look that issue 

![Screenshot 2023-08-29 at 14 10 59](https://github.com/Mijick/PopupView/assets/51842810/a28b0601-a0c9-492b-94a4-58627306d129)

**Comment by KavinduDissanayake** [comment]
![Screenshot 2023-09-26 at 22 57 56](https://github.com/Mijick/PopupView/assets/51842810/6075e0b2-91fd-4033-9a61-c6d9a3829357)

**Comment by FulcrumOne** [comment]
@KavinduDissanayake, the problem should be resolved with version 2.1.1
