### ISSUE TITLE
issue popup to stack bottom with center pop-up, 

### ISSUE THREAD

**Issue by KavinduDissanayake** [Mijick/PopupView#55]
![Simulator Screenshot - iPhone 12 - 2023-10-20 at 09 51 45](https://github.com/Mijick/PopupView/assets/51842810/f70fb8d8-d7a8-430d-92ac-763b8092e771)

Please help me to fixed it

**Comment by FulcrumOne** [comment]
Hi. The situation in the above screenshot is actually intentional - we wanted to enable all popups to be displayed at the same time. To close the selected popup, use stackAndReplace() or PopupManager.dismissAll(Popup.Type)
