### ISSUE TITLE
Feature request: Add an option to not apply gray background on top and bottom popup

### ISSUE THREAD

**Issue by gpfister-oskey** [Mijick/PopupView#56]
Hello,

Thank you for the great package. Would it be possible to add an option to not gray the background (on top or bottom popup) so that they can be use as toast.

**Comment by FulcrumOne** [comment]
Hey! 

Thank you very much for your comment. The feature has been implemented in the latest patch. Feel free to write other ideas, I'm open to new propositions :)

PS. You can find more SwiftUI packages here - https://github.com/Mijick, and the list is still growing.

Have a great day,
T.K.
