### ISSUE TITLE
Major issue - Bottom sheet with Center popup stack not align 

### ISSUE THREAD

**Issue by KavinduDissanayake** [Mijick/PopupView#59]
Always after opening the bottom stack when I try to open the center pop it will show on the background. please provide a solution and update the pod as well( I have different schema so I'm currently using your pod library)

![Simulator Screenshot - iPhone 15 Pro - 2023-10-25 at 17 12 26](https://github.com/Mijick/PopupView/assets/51842810/f7adeb85-86a8-4964-a463-16b5f4284470)

**Comment by FulcrumOne** [comment]
Hey! 

Thanks for your report. The bug has been fixed in the 2.2.0 patch. 

Have a nice day,
T.K.
