### ISSUE TITLE
Why is viewModel not deiniting with a PopupView?

### ISSUE THREAD

**Issue by baronha** [Mijick/PopupView#71]
I use popupView for a popup that confirms the user is leaving that screen. But the ViewModel cannot be denied when combined 
with the popupView, so in the long run it will lead to memory leaks.
<img width="292" alt="Screenshot 2024-03-01 at 01 09 18" src="https://github.com/Mijick/PopupView/assets/23580920/d9c4853a-4998-4947-b949-fc8cc4020f8f">

**Comment by baronha** [comment]
@FulcrumOne Any Update ?
Without your help I would have had to choose another solution even though PopupView suits me very well and it's really great.

**Comment by jay-jay-lama** [comment]
Hey!
Thank you for finding this issue. 
It's really good point that we didn't notice before. 
We are looking at this issue but unfortunately I can't say for sure when we will be able to fix it because we have not that much time for now.  
Sorry about that.

**Comment by FulcrumOne** [comment]
Hi @baronha,

I think we found the reason. We'll release the fix today or tomorrow.

**Comment by FulcrumOne** [comment]
@baronha, problem should be resolved in the branch patch-2.2.3

**Comment by baronha** [comment]
@FulcrumOne So amazing. Your efforts are wonderful !!

**Comment by FulcrumOne** [comment]
@baronha No problem. Sorry that this solution is kinda dirty, but we are currently swamped with the work. You can expect a new official update around April. 

Btw, we are going to create a section of apps built with our library, so if you want, you can send us a link to the app you are working on 🙂 

Have a great weekend!

**Comment by baronha** [comment]
> @baronha No problem. Sorry that this solution is kinda dirty, but we are currently swamped with the work. You can expect a new official update around April.
> 
> Btw, we are going to create a section of apps built with our library, so if you want, you can send us a link to the app you are working on 🙂
> 
> Have a great weekend!

No problem. I understand the countless busy jobs of an open source person. The above solution was my only salvation.
I will shoutout you on twitter for the beauty of this library. Thank you so much @FulcrumOne

**Comment by FulcrumOne** [comment]
Thank you, @baronha. If you find any other problems, please let us know. Even if our time is very limited, we'll try to help!

**Comment by FulcrumOne** [comment]
Fixed with #72
