### ISSUE TITLE
Crash while using Center Pop up on macOS

### ISSUE THREAD

**Issue by RizwanaDesai** [Mijick/PopupView#74]
App crashes when using center pop-up for macOS. Issue observed in demo app as well.

<img width="834" alt="Screenshot 2024-03-12 at 6 02 25 PM" src="https://github.com/Mijick/PopupView/assets/151725480/7eb5c6fd-ec8b-441a-aabd-a227063429f8">

**Comment by FulcrumOne** [comment]
Hey @RizwanaDesai,

I just checked and it works for me (such a cliche sentence 😄).
The error message from the image usually indicates some problem with Xcode - try to clean up & reload the project (even several times).

**Comment by RizwanaDesai** [comment]
Hey @FulcrumOne 
Appreciate your quick response. 
I tried after multiple clean-up and removed derived data as well but no luck. Still facing same crash.
I'm using xCode 15.1.

**Comment by FulcrumOne** [comment]
Hmmm, and the problem only affects CentrePopups? 
What version of iOS do you use?

**Comment by RizwanaDesai** [comment]
@FulcrumOne Yes problem only affect CentrePopups. 
Right now integrated this for macOS app and the my macOS version is 14.2

**Comment by FulcrumOne** [comment]
@RizwanaDesai The problem should disappear on the branch patch-2.2.4
Could you check it?

**Comment by itsthisjustin** [comment]
@FulcrumOne will check! Thanks for the quick reply.

**Comment by RizwanaDesai** [comment]
Yeah It's Fixed. Thanks a lot @FulcrumOne
