### ISSUE TITLE
How to use PopupView in muti Windows on macOS

### ISSUE THREAD

**Issue by TimorCan** [Mijick/PopupView#75]
Hi, i am very like popupView, but when use it in our macOS app, it's muti windows, when i pop it, it's show on every window, Do you have any advice

**Comment by FulcrumOne** [comment]
Hey @TimorCan, could you provide us with a screenshot (and/or a code) showing the problem?

**Comment by FulcrumOne** [comment]
@TimorCan, I tested it, and seems it works as it should on multiple windows:
https://github.com/Mijick/PopupView/assets/23524947/aecc14eb-c6d1-4139-958c-63367edb094a
