### ISSUE TITLE
macOS: Popups appears centered when in full-screen mode

### ISSUE THREAD

**Issue by RizwanaDesai** [Mijick/PopupView#76]
The top popup in the Mac OS app leaves unexpected extra space when the window size is slightly large and appears centered when in full-screen mode. Observed this issue in Demo app too.
<img width="1440" alt="Screenshot 2024-03-13 at 3 09 10 PM" src="https://github.com/Mijick/PopupView/assets/151725480/d3bb1b88-d19a-42c4-ad07-dbf18bfd80c2">
<img width="1250" alt="toppopup" src="https://github.com/Mijick/PopupView/assets/151725480/f28dd58a-5acd-49b3-87b7-e253c2c1cdaf">

**Comment by FulcrumOne** [comment]
hey @RizwanaDesai patch-2.2.4 should fix the issue

**Comment by RizwanaDesai** [comment]
Thanks @FulcrumOne. It's fixed.
For Top pop up i was expecting that it leaves space for toolbar and safe area. Well I'm looking into it.
<img width="1235" alt="Screenshot 2024-03-14 at 3 20 08 PM" src="https://github.com/Mijick/PopupView/assets/151725480/90646d87-be20-4319-a08d-9f04346d6a86">
