### ISSUE TITLE
Bottom sheet changes height upon scroll

### ISSUE THREAD

**Issue by greynguyen** [Mijick/PopupView#78]
It seems like there is a bug with scrolling quickly that causes the full screen bottom sheet to change height: https://share.cleanshot.com/Hlcr715R

**Comment by FulcrumOne** [comment]
Hey @greynguyen thanks for report! 

I'll check it and fix next week.

**Comment by FulcrumOne** [comment]
hey @greynguyen, did you modify your scroll view in any way?

**Comment by FulcrumOne** [comment]
Hey @greynguyen, the problem has been fixed in patch-2.2.4 branch
