### ISSUE TITLE
DismissAfter should be tied to a specific popup

### ISSUE THREAD

**Issue by dejiphonebox** [Mijick/PopupView#86]
I am setting dismiss after 4 seconds for example. if the user manually dismisses the first notification and a second one is triggered, the first dismiss after 4 that was set on a previous notification seems to dismiss the current notification

**Comment by FulcrumOne** [comment]
hey @dejiphonebox,

A branch named "patch-2.3.1" should fix the issue above. Could you please check and confirm this?

Thanks and have a great evening! 😉

**Comment by dejiphonebox** [comment]
Sure! Taking a look now

**Comment by dejiphonebox** [comment]
Works as expected now 👌🏼

**Comment by dejiphonebox** [comment]
Reopened because I think I shouldn't mark this as closed. Bug is fixed however :)

**Comment by FulcrumOne** [comment]
glad to hear it! I'll clean up the solution a bit and merge with the main bit later. 

thanks for help and don't hesitate to share any other bugs you notice! 😉
