### ISSUE TITLE
As a developer, I want to be able to use @EnvironmentObject in the popups

### ISSUE THREAD

**Issue by FulcrumOne** [Mijick/PopupView#89]

**Comment by gdetari** [comment]
+1

**Comment by Nathan1258** [comment]
+1

**Comment by FulcrumOne** [comment]
hey @gdetari, @Nathan1258, 

The request was implemented in patch-2.4.0 branch. Could you check it and confirm that everything works as expected? ;)

Thanks and have a nice day!

**Comment by Nathan1258** [comment]
@FulcrumOne I saw the branch minutes after I added the comment. Works great, thanks!

**Comment by FulcrumOne** [comment]
Thank you! Then I close the issue 😄
