### ISSUE TITLE
Stacking on different lanes

### ISSUE THREAD

**Issue by dentvii** [Mijick/PopupView#98]
I've encountered an issue when stacking different components on top of each other, such as SwiftUI views. This results in a weird animation glitch.

**Steps to Reproduce:**
1. Popup a fullscreen view.
2. From this fullscreen popup, popup a default bottom sheet view.

The animation behaves unexpectedly as shown in the example below.

**Additional Feature Request:**

It would be beneficial to have a feature that allows developers to set the priorities of popups, similar to the `zIndex` used internally. This would enable better control over the popup flow without requiring coordination between parts. For example:

1. **Example 1:** The user is on a settings configuration screen (a fullscreen popup) and receives a message (which should appear as a top popup). The message should overlay the view.
2. **Example 2:** The user receives a message on top of a fullscreen subscription paywall. The message should NOT be on top of the subscription paywall.

I would appreciate any help in resolving this issue.

![Simulator Screen Recording - Traft - iPhone 14 PM 16 4 - 2024-05-18 at 21 53 43](https://github.com/Mijick/PopupView/assets/87960/71cc3b16-dab5-447e-8c99-3e7bfe75440d)

**Comment by dentvii** [comment]
Thank you for your kindness and the effort you’re putting into this!

I believe the behavior is different from the fullScreen and sheet behavior in Apple's SwiftUI. I will isolate the code and share it here to make the issue reproducible.

**Comment by FulcrumOne** [comment]
@dentvii, any progress on that?

**Comment by dentvii** [comment]
I could not isolate the code to share so far, but I reproduced your example using the provided demo, and the issue is connected to glitch regarding [edgesFullScreen issue](https://github.com/Mijick/PopupView/issues/97). 

<img width="540" alt="image" src="https://github.com/Mijick/PopupView/assets/87960/59d75c47-9c7c-4f77-8448-e659a654e587">

As soon as I am able to test the branch I will update. Thanks again!

**Comment by FulcrumOne** [comment]
hey @dentvii,

This feature should be implemented in the branch patch-2.5.0:

![CleanShot 2024-06-01 at 02 08 31](https://github.com/Mijick/PopupView/assets/23524947/335620c6-7615-4c02-84c8-b2c576207c67)
